services:
  # Laravel App
  app-laravel:
    build: .
    container_name: laravel_project2_m4
    restart: always
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=36.50.55.56       
      - DB_PORT=3306
      - DB_DATABAS=qms
      - DB_USERNAME=root
      - DB_PASSWORD=admin123  # SỬA: Đã khớp với mật khẩu bên dưới
      - APP_DEBUG=true            # Bật để dễ xem lỗi nếu có
      - APP_URL=https://admin.vtbac.io.vn
      - ASSET_URL=https://admin.vtbac.io.vn
    volumes:
      - ./:/app
      - /app/vendor
      - /app/node_modules
      - ./storage:/app/storage
    networks:
      - m4_network

networks:
  m4_network:
    driver: bridge

volumes:
  db_data: