name: Deploy Laravel M4 (Single Container)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on Mac Mini
        run: |
          
          docker compose up -d --build
          echo "Đợi MySQL khởi động trong 20 giây..."
          sleep 20
          docker exec laravel_project2_m4 php artisan migrate --force
          docker exec laravel_project2_m4 php artisan config:cache